module.exports = {
  mySidebar: [
    'index',
    'Deploy Overview',
    'Deploy Terminology',
    {
      type: 'category',
      label: 'Deploy Administration',
      collapsed: true,
      items: [
        'Users',
        'Exercise 1',
        'Servers',
        'Exercise 2',
        'Settings',
        'Exercise 3',
        'Audits and Archiving',
        'Exercise 4',
      ],
    },
    {
      type: 'category',
      label: 'Deploy Scripts',
      collapsed: true,
      items: [
        'Scripts Overview',
        'Scripts Import Function',
        'Exercise 5',
        'Scripts Browse Function',
        'Exercise 6',
        'Scripts Deploy Function',
        'Exercise 7',
      ],
    },
    {
      type: 'category',
      label: 'Deploy Schedules & Packages',
      collapsed: true,
      items: [
        'Schedules Overview',
        'Schedules Import Function',
        'Exercise 8',
        'Schedules Browse Function',
        'Exercise 9',
        'Packages',
        'Packages Functions',
        'Exercise 10',
      ],
    },
    {
      type: 'category',
      label: 'Deploy Transformations',
      collapsed: true,
      items: [
        'Transformations Overview',
        'Transformations TagID List',
        'Transformations Functions',
        'Exercise 11',
        'Transformations Browse Function',
        'Exercise 12',
      ],
    },
    {
      type: 'category',
      label: 'Deploy Deployments & Browse Function',
      collapsed: true,
      items: [
        'Deployment Overview',
        'Deployment Function',
        'Deployment Simulation',
        'Exercise 13',
        'Batch Deployment Function',
        'Exercise 14',
        'Deployment Browse Function',
        'Exercise 15',
      ],
    },
    'Deploy Lab',
    {  
      type: 'link',
      label: 'Student Feedback Survey',
      href: 'https://forms.office.com/r/6tYjkNmfE5',
    },
  ],
};
