module.exports = {
  mySidebar: [
    'index',
    {
      type: 'category',
      label: 'Administration',
      collapsed: true,
      items: [
        'Deploy Overview',
        'Deploy Terminology',
        'Deploy Administration',
        'Deploy Exercise 1',
        'Administration - Servers',
        'Deploy Exercise 2',
        'Administration - Settings',
        'Deploy Exercise 3',
        'Administration - Audits And Archiving',
        'Deploy Exercise 4',
      ],
    },
    {
      type: 'category',
      label: 'Scripts',
      collapsed: true,
      items: [
        'Deploy Overview',
        'Deploy Terminology',
        'Deploy Administration',
        'Deploy Exercise 1',
        'Administration - Servers',
        'Deploy Exercise 2',
        'Administration - Settings',
        'Deploy Exercise 3',
        'Administration - Audits And Archiving',
        'Deploy Exercise 4',
        'Deploy Scripts',
        'Deploy Scripts - Imports',
        'Deploy Exercise 5',
        'Deploy Scripts - Deploy',
        'Deploy Exercise 6',
        'Deploy Exercise 7',
      ],
    },
    {
      type: 'category',
      label: 'Schedules & Packages',
      collapsed: true,
      items: [
        'Deploy Schedules',
        'Deploy Schedules Functions',
        'Deploy Exercise 8',
        'Deploy Exercise 9',
        'Deploy Packages',
        'Deploy Packages Functions',
        'Deploy Exercise 10',
      ],
    },
    {
      type: 'category',
      label: 'Transformations',
      collapsed: true,
      items: [
        'Deploy Transformations',
        'Deploy Transformations TagID List',
        'Deploy Transformations Functions',
        'Deploy Exercise 11',
        'Deploy Exercise 12',
      ],
    },
    {
      type: 'category',
      label: 'Deployments & Browse Function',
      collapsed: true,
      items: [
        'Deploy Deployment',
        'Deploy Deployment Schedules',
        'Deploy Deployment Simulation',
        'Deploy Exercise 13',
        'Deploy Batch Deployments',
        'Deploy Exercise 14',
        'Deployment Browse Function',
        'Deploy Exercise 15',
      ],
    },
    'Deploy Lab',
  ],
};
